config/routes.rb
Rails.application.routes.draw do
  devise_for :humans
  resources :humans
  resources :dogs
  root 'dogs#index'
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :human

  def human_name
    human.name
  end
end

app/models/human.rb
class Human < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :dogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_human!
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  respond_to :html
  before_action :set_dog, :only => [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_human!, :only => [:index, :show]

  def index
    @dogs = Dog.all
    respond_with(@dogs)
  end

  def show
    respond_with(@dog)
  end

  def new
    @dog = Dog.new
    respond_with(@dog)
  end

  def edit
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.save
    respond_with(@dog)
  end

  def update
    @dog.update(dog_params)
    respond_with(@dog)
  end

  def destroy
    @dog.destroy
    respond_with(@dog)
  end

  private

  def set_dog
    @dog = Dog.find(params[:id])
  end

  def dog_params
    params.require(:dog).permit(:name, :birthday, :gender, :human_id)
  end
end

app/controllers/humans_controller.rb
class HumansController < ApplicationController
  respond_to :html
  before_action :set_human, :only => [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_human!, :only => [:index, :show]

  def index
    @humans = Human.all
    respond_with(@humans)
  end

  def show
    respond_with(@human)
  end

  def new
    @human = Human.new
    respond_with(@human)
  end

  def edit
  end

  def create
    @human = Human.new(human_params)
    @human.save
    respond_with(@human)
  end

  def update
    @human.update(human_params)
    respond_with(@human)
  end

  def destroy
    @human.destroy
    respond_with(@human)
  end

  private

  def set_human
    @human = Human.find(params[:id])
  end

  def human_params
    params.require(:human).permit(:name, :birthday, :gender)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path)
    class_name = link_path.include?(params[:controller]) || current_page?(link_path) ? 'active' : ''
    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :human_id %><br>
    <%= f.collection_select :human_id, Human.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<% unless human_signed_in? %>
<div class="jumbotron">
  <h1>Welcome!</h1>
  <p>Airdogndog allows you to connect with other dog owners for doggie benefit.</p>
  <p>Arrange for a dog sitter, a puppy play date, or even find a dog to love on while you're traveling and stressed.</p>
  <p>
    <%= link_to 'Sign up to get started &raquo;'.html_safe, new_human_registration_path, :class => 'btn btn-lg btn-primary' %>
  </p>
</div>
<% end %>

<div class="row">
<% @dogs.each do |dog| %>
  <div class="col-md-4">
    <h2><%= dog.name %></h2>
    <p><i><%= dog.gender %> <%= distance_of_time_in_words dog.birthday, Date.today %> old</i></p>
    <p>Hi, I'm <%= dog.name %>, my human is <%= dog.human_name %>!</p>
    <p><%= link_to 'Show', dog, :class => 'btn btn-default' %></p>
  </div>
<% end %>
</div>

app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Birthday:</strong>
  <%= @dog.birthday %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @dog.gender %>
</p>

<p>
  <strong>Human:</strong>
  <%= @dog.human_name %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/humans/_form.html.erb
<%= form_for(@human) do |f| %>
  <% if @human.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@human.errors.count, "error") %> prohibited this human from being saved:</h2>

      <ul>
      <% @human.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday, :start_year => Time.now.year - 150, :end_year => Time.now.year, :max_years_allowed => 200 %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/humans/edit.html.erb
<h1>Editing human</h1>

<%= render 'form' %>

<%= link_to 'Show', @human %> |
<%= link_to 'Back', humans_path %>

app/views/humans/index.html.erb
<div class="row">
<% @humans.each do |human| %>
  <div class="col-md-4">
    <h2><%= human.name %></h2>
    <p><i><%= human.gender %> <%= distance_of_time_in_words human.birthday, Date.today %> old</i></p>
    <p>
      Hi, I'm <%= human.name %>,
      <% unless human.dogs.empty? %>
        I take care of <%= human.dogs.map(&:name).join(', ') %>!
      <% else %>
        I don't have any dogs yet :(
      <% end %>
    </p>
    <p><%= link_to 'Show', human, :class => 'btn btn-default' %></p>
  </div>
<% end %>
</div>

app/views/humans/new.html.erb
<h1>New human</h1>

<%= render 'form' %>

<%= link_to 'Back', humans_path %>

app/views/humans/show.html.erb
<div class="row">
  <div class="col-md-4">
    <h2><%= @human.name %></h2>
    <p><i><%= @human.gender %> <%= distance_of_time_in_words @human.birthday, Date.today %> old</i></p>
    <p>
      Hi, I'm <%= @human.name %>,
      <% unless @human.dogs.empty? %>
        I take care of <%= @human.dogs.map(&:name).join(', ') %>!
      <% else %>
        I don't have any dogs yet :(
      <% end %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airdogndog</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "#{image_tag 'logo.svg', :width => 220, :height => 50, :class => 'img-responsive'}".html_safe, root_path, :class => 'navbar-brand' %>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <!-- <li class="col-xs-2">
            <%= form_tag '/search', :class => 'navbar-form form-group' do %>
              <div class="input-group">
                <%= search_field_tag :search, '', :class => 'form-control input-sm', :placeholder => 'Search' %>
                <span class="input-group-btn">
                  <button class="btn btn-default btn-sm" type="button"><i class="glyphicon glyphicon-search"></i></button>
                </span>
              </div>
            <% end %>
          </li> -->
          <%= nav_link 'Dogs', dogs_path %>
          <%= nav_link 'Humans', humans_path %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if human_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_human.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to 'Profile', edit_human_registration_path %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to('Sign out', destroy_human_session_path, :method => :delete) %>
                </li>
              </ul>
            </li>
          <% else %>
            <li>
              <%= link_to('Sign in', new_human_session_path) %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>